services:
  app:
    build: .
    ports:
      - "5002:5000"
    environment:
      PORT: 5000
      SQLITE_DB_PATH: /app/data/database.db
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data: